// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yotwifbiutluqljnhgue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdHdpZmJpdXRsdXFsam5oZ3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjQ1MTgsImV4cCI6MjA1ODM0MDUxOH0.qG7BANOB9kl4S4LpjsqUpIHbyYGc4ThwlpR7_OM-U4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);